[package]
name = "Rustenstein3d"
version = "0.1.0"
authors = ["still"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
